### PR TITLE
Update to cursive 0.17

### PR DESCRIPTION
**Pull request by gyscos**
The version of rust_sodium from crates.io links to an old version of
lazy_static, incompatible with what Cursive 0.17 requires (through
crossbeam).
The git repository has been updated (for almost 2 years now), but that
has not been pushed to crates.io.

This PR updates Cargo.toml to point to the git repo of rust-sodium.
That being said, this particular repository appears abandoned.
The link to SubSpace included in the repo is dead as well.

### CODE REVIEW

**Comment by threema-danilo** [comment]
Hi, I just merged #74, which replaces `rust_sodium` with pure-Rust crates from the RustCrypto ecosystem. The `rust_sodium` crate is dead, which caused a lot of maintenance issues in this project as well. I hope this will now become easier, especially since no more C dependencies are included.

Would you like to rebase your PR?

**Comment by threema-danilo** [comment]
By the way, very nice of you to send PRs to downstream crates! Thanks 🙂

**Comment by gyscos** [comment]
Rebased :)

Pretty easy update in the end.

**Comment by threema-danilo** [comment]
Great, thanks!

There was a CI mis-configuration that should now be fixed, I'll amend your commit to trigger CI.

**Comment by threema-danilo** [comment]
Huh, I have no idea what just happened, I just tried to push an update to your branch 😕

I'll cherry-pick it onto a new PR, sorry about that.

**Comment by threema-danilo** [comment]
> I'll cherry-pick it onto a new PR, sorry about that.

Done in #77.

**Pull request closed without merging**
